export { AdvertCard } from './AdvertCard/AdvertCard'
export { ExtensionCard } from './ExtensionCard/ExtensionCard'
export { CardContent } from './FirstCard/card-content'
export { NewsData } from './NewsCard/NewsData'
export { NewsCard } from './NewsCard/NewsCard'
export { NewsHeader } from './NewsCard/NewsHeader'
export {CardContentTwo} from './SecondCard/CardContentTwo'